export const headers = [
  [
    "Employee ID",
    "Name",
    "Mobile Number",
    "Email",
    "Gender (M/F/T)",
    "Nationality",
    "Date of Birth (dd/mm/yyyy)",
    "Date of Joining (dd/mm/yyyy)",
    "Aadhaar Number",
    "PAN Number",
    "Bank Account Holder Name",
    "Bank Account Number",
    "Bank IFSC Code",
    "Name of Principal Employer",
    "Job Title",
    "Business Unit (Optional)",
    "Annual CTC",
    "PF UAN (Enter if available else leave blank)",
    "Employer Establishment Code (Username for ESIC Login)",
    "ESIC Number (aka IP Number) (Enter if available else leave blank)",
    "Father's / Husband's Name",
    "Relation with Employee (Father / Husband)",
    "Marital Status (Married,Un-married,Widow/Widower,Divorcee)",
    "Employee Present Address",
    "Employee Present Address District",
    "Employee Present Address State",
    "Employee Present Address Pincode",
    "Employee Permanent Address",
    "Employee Permanent Address District",
    "Employee Permanent Address State",
    "Employee Permanent Address Pincode",
    "Name of Nominee (As per Aadhaar card)",
    "Nominee Relationship with Employee",
    "Nominee Address",
    "Nominee Address District",
    "Nominee Address State",
    "Nominee Address Pincode",
  ],
];
